debug: true
spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: tis-revalidation-recommendation
  jackson:
    serialization.write_dates_as_timestamps: false
    serialization.indent_output: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    ssl.enabled: ${RABBITMQ_USE_SSL:false}
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:root}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:revalidation}?authSource=admin&authMechanism=SCRAM-SHA-1

server:
  servlet:
    context-path: /revalidation
  port: ${SERVICE_PORT:8080}

logging:
  level:
    uk.nhs.hee.tis.revalidation: ${LOGGING_LEVEL:INFO}
    org.springframework.data.mongodb.core.MongoTemplate: ${LOGGING_LEVEL:ERROR}
    org.springframework.boot.autoconfigure: ${LOGGING_LEVEL:ERROR}

  file:
    name: ${LOG_DIR:${HOME}}/revalidation.log

management:
  endpoints:
    health:
      enabled: true
    web:
      exposure:
        include: '*'
  server:
    servlet:
      context-path: /management

app:
  error:
    exchange: "ex.error"
    limit.retries: true

  reval:
    event.store.db: ${EVENT_STORE:eventstore}
    event.store.collection: ${EVENT_STORE_COLLECTION:events_log}
    pagination.pageSize: ${PAGINATION_PAGE_SIZE:20}
    tcs.url: ${TCS_URL:http:localhost:8080/tcsmock/api/revalidation}

  validation:
    sort.fields: ${SORT_FIELD:submissionDate,doctorFirstName,doctorLastName,gmcReferenceNumber}
    sort.order: ${SORT_ORDER:asc,desc}

  rabbit:
    exchange: ${EXCHANGE:reval.exchange.gmcsync}
    queue: ${QUEUE:reval.queue.gmcsync.recommendation}
    routingKey: ${ROUTING_KEY:reval.gmcsync}
    connection.queue: ${CONNECTION_QUEUE:reval.queue.connection.manualupdate.recommendation}
    connection.routingKey: ${CONNECTION_ROUTING_KEY:reval.connection.manualupdate}
    reval.exchange: ${REVAL_RABBIT_EXCHANGE:reval.exchange}
    reval.queue.recommendation.syncstart: ${REVAL_RABBIT_RECOMMENDATION_SYNC_START_QUEUE:reval.queue.recommendation.syncstart}
    reval.routingKey.recommendation.syncstart: ${REVAL_RABBIT_RECOMMENDATION_SYNCSTART_ROUTING_KEY:reval.recommendation.syncstart}
    reval.routingKey.recommendationstatuscheck.requested: ${REVAL_RABBIT_RECOMMENDATION_STATUS_CHECK_REQUESTED_ROUTING_KEY:reval.recommendationstatuscheck.requested}

  gmc:
    url: ${GMC_CONNECT_URL:http://localhost:8090/GMCConnectMock2020/GMCWebServices}
    soapActionBase: ${GMC_SOAP_ACTION_BASE:https://webcache.gmc-uk.org/GMCWebServices/}
    gmcUsername: ${GMC_USER_NAME:guest}
    gmcPassword: ${GMC_PASSWORD:guest}
    designatedBodies: ${DESIGNATED_BODY_CODE:1-AIIDHJ,1-AIIDMQ,1-AIIDNQ,1-AIIDMY,1-AIIDQQ,1-AIIDWT,1-AIIDR8,1-AIIDSA,1-AIIDH1,1-AIIDWA,1-AIIDVS,1-AIIDWI,1-AIIDSI}
    recommendationstatuscheck.cronExpression: ${REC_STATUS_CHECK_CRON:0 0 * * * *}

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:}

cloud:
  aws:
    end-point:
      uri: ${SQS_SYNC_GMC_QUEUE:}

mongock:
  change-logs-scan-package: uk.nhs.hee.tis.revalidation.changelog